import express from "express";
import { organizationsPage } from "./organizations.js";
import { indexPage } from "./index.js";
import { projectsPage } from "./projects.js";
import { categoriesPage } from "./categories.js";
import { testErrorPage } from "./errors.js";
import { showOrganizationDetailsPage } from "./organizations.js";
import { showProjectDetailsPage } from "./projects.js";
import { showCategoryDetailsPage } from "./categories.js";
const router = express.Router();
router.get("/organizations", organizationsPage);
router.get("/", indexPage);
router.get("/projects", projectsPage);
router.get("/categories", categoriesPage);
router.get("/test-error", testErrorPage);
router.get("/organization/:id", showOrganizationDetailsPage);
router.get("/project/:id", showProjectDetailsPage);
router.get("/category/:id", showCategoryDetailsPage);

export default router;
